name: SSH Connectivity Test

on:
  workflow_dispatch:  # manual trigger

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu                     # or ec2-user (depends on your AMI)
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ SSH connection succeeded!"
            hostname
            uptime